name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest

    env:
      TF_BACKEND_BUCKET: "my-terraform-state-bucket"
      TF_BACKEND_KEY: "dev/terraform.tfstate"
      TF_BACKEND_REGION: "us-east-1"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform Init
      run: |
        pwd
        cd Infrastructure-AWS-main/terraform/environments/dev
        pwd
        terraform init \
          -input=false


    - name: Terraform Validate
      run: |
        pwd
        cd Infrastructure-AWS-main/terraform/environments/dev 
        terraform validate

    - name: Terraform Plan
      run: |
        pwd
        cd Infrastructure-AWS-main/terraform/environments/dev 
        terraform plan -var-file=dev.tfvars -out=dev.tfplan

    - name: Terraform Apply
      run: |
        cd Infrastructure-AWS-main/terraform/environments/dev
        terraform apply -auto-approve dev.tfplan
